### ISSUE TITLE
RequestError: 3070065568:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:

### ISSUE THREAD

**Issue by alatteri** [bitfocus/companion-satellite#64]
Installing on fresh Armbian.

```
error /home/satellite/companion-satellite/node_modules/@types/electron-prompt/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/satellite/companion-satellite/node_modules/@types/electron-prompt/node_modules/electron
Output:
RequestError: 3070065568:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:

    at ClientRequest.<anonymous> (/home/satellite/companion-satellite/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/home/satellite/companion-satellite/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)


```

**Comment by Julusian** [comment]
I don't have any suggestions here, this reads like something with openssl has gotten messed up, or perhaps with nodejs generally on the system. As this isnt happening on other distros, and I have no experience with armbian I won't be much help.

**Comment by alatteri** [comment]
OK....It works anyway, even with the error during compile.  I actually think it might be related to a missing hardware function, as this is on a very small SBC, Orange ZeroPi.   Closing.
